;==================================================
;
;              ALLAN JPA ~~ SEASON 14 FULL
;                  SENIOR PROFISSIONAL
; [ WHATSAPP ]     
; [ NUMBER   ]     *22 999518600
; [ URL      ] www.AprendizMuOnline.com.br           
;
;==================================================
;
[JoinServerInfo]
;==================================================
; Basic Settings
;==================================================
JoinServerODBC = MuOnlineS14
JoinServerPort = 55970
ConnectServerAddress = 127.0.0.1
ConnectServerPort = 55557
CaseSensitive = 0
MD5Encryption = 0
ChangePersonalCode = 1