;==================================================
;
;              ALLAN JPA ~~ SEASON 14 FULL
;                  SENIOR PROFISSIONAL
; [ WHATSAPP ]     
; [ NUMBER   ]     *22 999518600
; [ URL      ] www.AprendizMuOnline.com.br           
;
;==================================================
;
[ConnectServerInfo]
;==================================================
; Basic Settings
;==================================================
ConnectServerPortTCP = 44405
ConnectServerPortUDP = 55557
MaxIpConnection = 10
MaxPacketPerSecond = 5

;==================================================
; Auto Update Settings
;==================================================
Version = 
VersionFile = 
HostURL = 
FTPLogin = 
FTPPasswd = 
FTPPort = 

;==================================================
; DB Settings
;==================================================
ConnectServerODBC = MuOnlineS14